spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notes_app?useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#logging development configuration
logging:
  config: src\main\resources\logback-development.xml